# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Movies CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 14.x
      uses: actions/setup-node@v3
      with:
        node-version: 14.x
        cache: 'npm'
    - name: Installing NPM
      run: npm install
    - name: Running Unit Tests
      run: npm run test:unit
    - name: Display SoftUni Username
      run: echo "ivo-ns"
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Deploy to Prod
    # You may pin to the exact commit or the version.
    # uses: johnbeynon/render-deploy-action@a0588f9aca995a15d69a72cb2bfbf37c12e5b540
      uses: johnbeynon/render-deploy-action@v0.0.8
      with:
    # ID of the service to deploy
        service-id: ${{ secrets.RENDER_SERVICE_ID }}
    # A Render API key
        api-key: ${{ secrets.RENDER_API_KEY }}
  ui-tests:
      runs-on: ubuntu-latest
      needs: deploy
      steps:
        - uses: actions/checkout@v3
        - name: Use Node.js 14.x
          uses: actions/setup-node@v3
          with:
            node-version: 14.x
            cache: 'npm'
        - name: Installing NPM
          run: npm install
        - name: Install Playwright Browsers
          run: npx playwright install --with-deps
        - name: Running UI Tests
          run: npm run test:ui
